language: node_js
node_js:
  - stable
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
after_success:
  - npm run coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
